kind: ENC[AES256_GCM,data:00ABrJGY,iv:3sPTCRosYvsWH8fwLhMfuPxNlVxoLR7Wa8+WMq/cEFU=,tag:pd0K0okP6NPRofo6OnEdXw==,type:str]
ansible_user: ENC[AES256_GCM,data:PAEXe7o=,iv:dbwLiaYQ5GWxkwlG9nQ4sJB2Un8TJniRy/ZX/QytgfA=,tag:wThk9d96ocd6z6l/mJhGeg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:gFZ/MaAVru8=,iv:YWqsDyiDllzYaLKClfvmBydO6BsxecE0JheGVJrW2TI=,tag:6tq0RQjwjjgZ3BHM2n8xEg==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: 5ED5AC4897B3E2EB
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyH4Jv2F6yUtAQ//YoZkfr4xqdQ0Xcj0cvB1IxdrcGg8hGeGiwZGsPNa6m0h
            R09SjUzD3Lzla+hy9wiVuNb0IzcEgJ/U0Vo6TWkDv+IS7HqJT64GSGfhRhPx37VC
            0F/65KriC/8Cq3vXxIHNTQm6mQcuTGW/eCloWakgBb63+cNwaEzOD9B+oQKSFojT
            vq1JXvH4Q+dA3f1mr/2oDh6C0Ip4jI1eDB7cmJ5aKHPuCfKKHCX2RgLfcGZyl3UO
            nAzwG5orooLpThkIJxkeIAC6iJ5pPQwSmiAZaV1Yg9ReUAhqZyuTfOS1BKmwTGAQ
            Y6VM4SMnJxyncay9AS+hf0cCJtpjFN9oIucRELxvFXj3b56SbUhQI2uNtBfYq6v4
            Z11f41bgySLidQH2U4zKGa9nig5eTMzLENnlXUkprvw7iSe6CfJ5ZBnjRZ75k7fm
            dU4UiE6pg0VldOpc2ex0Ak9kLe4M6X6iTvwg3ASAJ/DViBZQ/7RkR1UTdjDlHgVZ
            cY5MfgO4W5Si2bT0pFVCVlLp+ed8228JTY8j3lOc9clAwcG5IgpIEk6rQdT5Oa4J
            +R+b+dS3+nHpoWthbBkaXGEZQv88GcPsgo5dFVSe7pGRLPcsG07Sjr1iS6qWge5G
            bimMl90VhO+Ntgp5eKkAaYDP30IGM+cj/+7tUN/1it3Z0cvJxKafdf6ARWYbthHS
            XgF6SUTE6e3iZeodn0HZKZ93IUdu7uVpRIx4AIaMI4JfPf6OfAp17v4eaUwu6U9I
            4YiAcCKhO0/HSzGuP9vgJd6iyVrxJeqPh/IPQxJMyXsUk6UV3hPqNkPFu78ACYs=
            =Pa+t
            -----END PGP MESSAGE-----
        created_at: '2021-10-22T02:03:16Z'
    lastmodified: '2021-10-22T02:03:16Z'
    mac: ENC[AES256_GCM,data:HJmRyrP6spgdxN5TOTiiBq8acRL59pfw/NwKCi2wPkB3crbKLy+UVBbQQhiLzwZdFqNe+sEBE0PajgN4+fFZsnor0PH6WY+dvht4Vx1lsElstvNjCMPqruK8jEO5CleQYmVcUDsBVuyAVM5EJJjv1q5M4p4PxTi4kyWjuKEyYz0=,iv:MICm6Jr2lstt9rx9r2thBUthSb0ZaPLL4CyEdjGKb00=,tag:oO/9RsqGW8f/O755TQGaUA==,type:str]
