# yamllint disable
apiVersion: ENC[AES256_GCM,data:ltw=,iv:4Kz+1zoN4dH4Irb7lYOXWdMcLp61PPDxE7Voa7ZhmBc=,tag:B7gA7MwfY2Z+hNc/HGt1ug==,type:str]
kind: ENC[AES256_GCM,data:9xgkbM2I,iv:qo0PZNCvZNv7ABuQv0a+Yc7wW2x4vVo8ACx0L+gLZhI=,tag:6O3/SSU19tiNvizwDBeKGQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+Zn+Qj/o/Fa36eJrythiBMLf,iv:SpfUEwPPqPfPrRPYUBzlSdA2JC+NS4oPVqO0K5budBA=,tag:UgFK9PUtI/xvnDadK6E/2w==,type:str]
    namespace: ENC[AES256_GCM,data:4zHqs2ix3e5MR60o,iv:CY3cz88zZXpS2WeU2xQWu7ff2Q5Up10U2Z3lHRB0Mxo=,tag:4wtj7eqvNN9xv7IXaI7qYQ==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:3Sr+45CnpOrfTsLwiLPOITQIa6VBruSciZZdc6AxvY2zvXpKmw==,iv:dZr1o7E9pMjp3R+YBqJ4YoHF8ClwR8d7p68eCDNiZwg=,tag:jV6toXmBWWfZ5BprTKGYyw==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: 5ED5AC4897B3E2EB
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyH4Jv2F6yUtAQ//f0tS0t6aWXRsnqU5WQRtPIyfGD+rvUVzjzC22emiA8QU
            tSE3rQPXx2IyQc8b6KPZtOgj1PZ+8qKmOZclv3pCCFoUHtadGFy7WadGycMB55Fo
            hKFTAu4GpV8oNd0bWnTQUVUPUnL23WURC5IhthJM5jGVIJYv83jr/Ef0fDg8xmp7
            FDYg2KW71qDMPhDMpJefiZrwjIol9HZP4w0Et5VuGFm8YFGCzNGqnOrDsf1eNsL7
            9CcRRejSDM0UOLRIQbbYU9W9WtYb5+BSK6GHh/HKs6I+wPy5OHwbLR8HrLI8yMn+
            udzlv6pjTVAEpE6kC7xRJmWPF+rVAe0MI4T48DUV/y76aWngVdTYbLanIMBFnegE
            Fxhu7zB2EfKUwpp+RqmcG/Ab6s82tR7Sx89T4HMwQzK94bvXsOW2bEi+1wQLOiCG
            42mfp5L/1HnCMRBivXUiEBO1w6fDUPiXCMHMdUYjZSSbYO+tzYHU8igp54XHHU4A
            Fo2B1WGZ0LLGHR5skbCL31y1B9mLsQYHMribYCpsKTDAix13e8j8SjkGyfYs6v63
            4QzLkbHvgcGj2WvUCTzHA6bscqn2iC76FLpl+33Fy4kPPuO7C7P6sNuyEmnLzpKw
            XcZwS7saI1GowhozIxnOorh1s5rLJU/C+IcFZq2aFPILUpzMCZkVywaqfwrk627S
            XgGdpRusFNJJZs9hxjhE4sdb9KNkXyqqftyQMoE9IE35KkHzRtkrDevpKtiJvRSD
            phs/Mo+VobpTp7Hmc8FBvDGYzRd53ea1h/khBzGO7TdorO1fDT/nRrFjSgkFyRc=
            =L6jQ
            -----END PGP MESSAGE-----
        created_at: '2021-10-22T02:03:15Z'
    lastmodified: '2021-10-22T02:03:15Z'
    mac: ENC[AES256_GCM,data:aoDFmroxMe2flYNcHb95llams7o2esAMghADPbKDA4TdTmYnXMe9bfpeao2zXmQN+oooObpyMk++Kvo1yVtv/l3L8ukRzFRGk1Bx6fMrAgm7wV2CAqHga87Uq1ZR9FDx9Loekd9+Xbg+ZOK+J3DGmEl2SttEh/dASODln/UspYU=,iv:M5yFm6w/nXV2dFrJYqqRLr3NC+a+A2QyEd8Pr+il/rE=,tag:G5bUbiKeAaFbPNrTe0omzw==,type:str]
